### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [Camnooten/RobloxPy#2]
At the moment, there is a syntax for being able to return information, it would be useful if you could use admin with the group, e.g Rank people

**Comment by cameronthecoder** [comment]
Hi, thanks for checking this repo out. I am so sorry I didn't see your issue earlier, I didn't get notified about it. What method/syntax are you talking about? I am a little confused.

**Comment by cameronthecoder** [comment]
No response so I am going to close this issue.
