### ISSUE TITLE
Finding a user's badges doensn't working

### ISSUE THREAD

**Issue by notlorick** [Camnooten/RobloxPy#3]
When im trying to get user's badges i getting this error:
Traceback (most recent call last):
  File "C:\Users\lorick\Documents\atom\python\roblox\123.py", line 1, in <module>
    import robloxpy
  File "C:\Users\lorick\Documents\atom\python\roblox\robloxpy.py", line 1, in <module>
    import requests
ImportError: No module named requests

But i have robloxpy.py and other commands working

**Comment by iranathan** [comment]
The module `requests` is not installed. You can do so by doing: `pip install requests`

**Comment by cameronthecoder** [comment]
Oh my gosh, why didn't I think of that :man_facepalming:. Anyway, thanks helping out in this issue. I am working on updating the wrapper so it is more organized.
